*** Variables ***
&{checkout_payment_invoice_date_of_birth_field}    b2c=id=paymentForm_dummyPaymentInvoice_date_of_birth    b2b=id=paymentForm_dummyPaymentInvoice_date_of_birth    mp_b2c=id=paymentForm_dummyMarketplacePaymentInvoice_dateOfBirth
${checkout_payment_cc_card_number_field}    id=paymentForm_dummyPaymentCreditCard_card_number
${checkout_payment_cc_name_on_card_field}    id=paymentForm_dummyPaymentCreditCard_name_on_card
${checkout_payment_cc_card_expires_month_dropdown}    id=paymentForm_dummyPaymentCreditCard_card_expires_month
${checkout_payment_cc_card_expires_year_dropdown}    id=paymentForm_dummyPaymentCreditCard_card_expires_year
${checkout_payment_cc_card_cvc_code_field}    id=paymentForm_dummyPaymentCreditCard_card_security_code